pipeline {
    agent any
    stages {
        
        stage('compile stage') {
          steps {
              withMaven(maven : 'maven') {
              sh 'mvn -f pets clean compile'
              }
          }
        }

        stage('Test') {
          steps {
              withMaven(maven : 'maven') {
              sh 'mvn -f pets test'
              }
          }
        }

        stage('install') {
          steps {
              withMaven(maven : 'maven') {
              sh 'mvn -f pets install'
              }
          }
        }
    }
}