pipeline{
    agent any
    stages{
        stage('compile stage'){
          steps{
              withMaven(maven: 'maven')
              sh 'mvn clean compile'
          }
        }

        stage('Test'){
          steps{
              withMaven(maven: 'maven')
              sh 'mvn test'
          }
        }

        stage('deploy'){
          steps{
              withMaven(maven: 'maven')
              sh 'mvn deploy'
          }
        }
    }
}
